### ISSUE TITLE
[bug]: package binary+keys for fzf does not config keybindings correctly.

### ISSUE THREAD

**Issue by glyh** [zdharma-continuum/zinit-packages#7]
### Describe the bug

Use the following zshrc:
```zsh

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk

zinit pack"binary+keys" for fzf

```

### Steps to reproduce

1. Run zsh once to init zinit plugins
2. restart zsh.

### Expected behavior

keybindings for fzf works, but it shows this:
```
.zinit-load-plugin:source:59: no such file or directory: /home/lyh/.local/share/zinit/plugins/fzf/key-bindings.zsh
```

### Screenshots and recordings

Here's the video when initing zinit:
[![asciicast](https://asciinema.org/a/RMHRvDPfKV2tbzFnIgKanMlVx.svg)](https://asciinema.org/a/RMHRvDPfKV2tbzFnIgKanMlVx)

It's from the [other issue](https://github.com/zdharma-continuum/zinit-annex-patch-dl/issues/5)

### Operating System & Version

linux-gnu | pc | x86_64 | x86_64 | x86_64 unknown

### Zsh version

zsh 5.9 (x86_64-pc-linux-gnu)

### Terminal emulator

alacritty

**Comment by ryaminal** [comment]
[Fix is in this PR](https://github.com/zdharma-continuum/zinit-annex-patch-dl/pull/4)

Would appreciate someone okaying the PR or looking at it.
